name: Update Profile Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Update every 12 hours
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          base: ""
          config_timezone: Asia/Tokyo
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_facts: no
